appGuide/en.html
appGuide/kr.html
styles/css/appGuide.css
styles/scss/pages/appGuide.scss
styles/scss/pages/application.scss

-  appGuide 웹뷰 페이지 퍼블리싱
- banner, header, footer 모두 없애고 Main Page부터 보여줍니다.
- 애니메이션 제거
- 상단 간격 10px 줄이고, 하단 간격 10px 늘렸습니다.
- 앱가이드 한글 & 영어버전만 사용
- 조과장님, 도희팀장님 리뷰받고 반영했습니다.

appGuide 웹뷰 페이지 퍼블리싱

---

index.html
styles/css/index.css

Fix: index.css 파일

---

styles/css/event.css
styles/scss/pages/event.scss

FIX: 북앤라이프 이벤트 배경이미지 path수정안된거 추가

---

styles/css/event.css
styles/scss/pages/event.scss

Revert "FIX: 북앤라이프 이벤트 배경이미지 path수정안된거 추가"

---

paysevents/index.html
styles/css/event.css
styles/scss/pages/event.scss

FIX: 북앤라이프 이벤트 유의사항 및 이미지경로 수정

---

paysevents/index.html
styles/css/event.css
styles/scss/pages/event.scss

Revert "FIX: 북앤라이프 이벤트 유의사항 및 이미지경로 수정"

---

cn/apptech/tech.html
en/apptech/tech.html
kr/apptech/tech.html

- FIX: TECH페이지 MVC교환수단 항목 제거
- 변경전 
- 변경후

FIX: TECH페이지 MVC교환수단 항목 제거

---

cn/index.html
index.html
kr/index.html

FIX: 공지사항 팝업 주석처리

---

events/index.html

FIX: 스타벅스 이벤트 렌더링 유의사항추가

---

appGuide/en.html
appGuide/kr.html

- 모바일용 이미지를 사용했는데 뿌옇게 보여서 이미지 교체했습니다.

fix: 앱가이드 이미지 교체

---

cn/common/footer.html
en/common/footer.html
kr/common/footer.html

- 대표자 이름: William Jung, 鄭鎭馨(중문PC버전)
- 대표자 이름과 사업자 등록번호가 한줄 
- 대표자 이름: William Jung (Jinhyung Jung)
- 대표자 이름 및 사업자 등록번호 줄 바꿈
- eslint적용으로 코드가 수정되었습니다.

fix: 영문, 중문 footer 대표자 이름 수정 및 줄바꿈추가

---

events/index.html
styles/css/event.css
styles/css/font.css
styles/scss/pages/event.scss

돈방석 랜딩페이지 문구 및 스타일변경

---

pop/kr/notice.html

개인정보처리방침 변경고지 v1.4 개정시행일자 수정

---

cn/common/footer.html
en/common/footer.html
kr/common/footer.html

feat: 한글, 영문 백서 URL변경

---

cn/company/mileverse.html
en/company/mileverse.html
kr/company/mileverse.html

`../../assets/img//mileverse/run.png` → `../../assets/img/mileverse/run.png`

fix: 로드맵 이미지 path 오타수정

---

cn/common/footer.html
en/common/footer.html
kr/common/footer.html

feat: 홈페이지 주소 변경

---

find/address.html

feat: 실물쇼핑 주소검색 웹뷰

---

.well-known/apple-app-site-association
kr/common/footer.html

feat: 간편 로그인 webcredentials 설정

---

cn/index.html
index.html
kr/index.html

fix: 앱스토어 오타수정

---

cn/apptech/application.html
cn/common/header.html
cn/index.html
en/common/header.html
en/index.html
en/js/index.js
index.html
kr/common/header.html
styles/css/animation.css
styles/css/application.css
styles/css/banner.css
styles/css/bookcash.css
styles/css/business.css
styles/css/contact.css
styles/css/footer.css
styles/css/header.css
styles/css/home.css
styles/css/index.css
styles/css/layout.css
styles/css/privacy.css
styles/css/tech.css
styles/scss/components/header.scss
styles/scss/index.scss
styles/scss/pages/home.scss

- 기존 kr/index.html → index.html
- 기존 index.html → en/index.html
- 데스크탑, 모바일 헤더에서 링크변경

홈페이지 기본상태 국문으로 변경

---

cn/common/footer.html
en/common/footer.html
kr/common/footer.html
styles/css/footer.css
styles/css/index.css
styles/scss/components/footer.scss

footer 리팩토링 및 2.4버전 백서 업데이트

---

cn/common/footer.html
en/common/footer.html
kr/common/footer.html

240909 대표님 지시사항으로 진기팀장님 요청
구글드라이브 링크는 한글버전만 있음 (영/중문 없음)

feat: footer Design Guide → MVC 보유량
